title: "Debarshi Mukherjee | Physics Enthusiast"
author: "Debarshi Mukherjee"
description: "Final year masters student majoring in physics"
theme: jekyll-theme-minimal
baseurl: "/debarshiphysics09.io"

